### ISSUE TITLE
Wrong event names in etc/init/xbmc.conf

### ISSUE THREAD

**Issue by stsichler** [xbianonpi/xbian-package-xbmc-scripts#7]
The etc/init/xbmc.conf script uses wrong/obsolete event names with xbmc-send.py, see
https://github.com/xbianonpi/xbian-package-xbmc-scripts/blob/0895fd1baf5cb6d26094032577f87a5cf3738e60/content/etc/init/xbmc.conf#L104

These only result in log entries like `ERROR <general>: Keymapping error: no such action 'xbmc.quit' defined` and are ignored by kodi.
The 'xbmc' prefix must be removed from the event names here, it seems to be obsolete.

**Comment by mkreisl** [comment]
Thanks for the hint. 
I don't get an error message, but no action is carried out either.

**Comment by stsichler** [comment]
Hm... strange that you don't get that error....
 
Btw. is there a specific reason for this script using the xbmc-send.py script instead of the native kodi-send binary from kodi-eventclients-kodi-send package? (I'm just curious)

**Comment by mkreisl** [comment]
Originally the script was called **xbmc-send.py**. today it is just a link to k**odi.send.py**

**Comment by stsichler** [comment]
This is not what I meant. I know that xbmc was renamed to kodi, but why do you use a custom `/usr/local/bin/kodi-send.py` instead of the original `/usr/bin/kodi-send` script from the `kodi-eventclients-kodi-send` package?
But I think I already see the reason: There is a slight difference between them:
```
> diff /usr/bin/kodi-send /usr/local/bin/kodi-send.py 
1c1
< #! /usr/bin/python3
---
> #!/usr/bin/env python3
```

**Comment by mkreisl** [comment]
The package you are referring to is an ancient one, dating back to the time of kodi 17.
I use it directly from the kodi sources, with the soon to be updated package xbian-package-xbmc-scripts comes a new version with new features, see https://github.com/xbmc/xbmc/commits/master/tools/EventClients/Clients/KodiSend/kodi-send.py

**Comment by mkreisl** [comment]
Fixed
